# This is a basic workflow to help you get started with Actions

name: Check latest Chrome version

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '16 5,20 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: chrome --headless --disable-gpu --dump-dom https://ja3er.com/json
